export interface CSSProperty {
  name: string
  description: string
  syntax: string
  values: string[]
  example: string
  category: string
  subcategory?: string
  browserSupport: string
}

export const cssCategories = {
  layout: {
    title: "Layout & Positioning",
    icon: "Layout",
    color: "from-blue-500 to-cyan-500",
    subcategories: {
      display: "Display",
      position: "Position",
      flexbox: "Flexbox",
      grid: "Grid",
      float: "Float & Clear",
      columns: "Multi-column",
    },
  },
  typography: {
    title: "Typography",
    icon: "Type",
    color: "from-purple-500 to-pink-500",
    subcategories: {
      font: "Font Properties",
      text: "Text Properties",
      lineHeight: "Line & Letter Spacing",
      textDecoration: "Text Decoration",
      textTransform: "Text Transform",
    },
  },
  colors: {
    title: "Colors & Backgrounds",
    icon: "Palette",
    color: "from-orange-500 to-red-500",
    subcategories: {
      color: "Color",
      background: "Background",
      gradient: "Gradients",
      opacity: "Opacity & Blend",
    },
  },
  boxModel: {
    title: "Box Model",
    icon: "Box",
    color: "from-green-500 to-emerald-500",
    subcategories: {
      margin: "Margin",
      padding: "Padding",
      width: "Width & Height",
      boxSizing: "Box Sizing",
    },
  },
  borders: {
    title: "Borders & Outlines",
    icon: "Square",
    color: "from-indigo-500 to-blue-500",
    subcategories: {
      border: "Border",
      borderRadius: "Border Radius",
      outline: "Outline",
      boxShadow: "Box Shadow",
    },
  },
  animations: {
    title: "Animations & Transitions",
    icon: "Zap",
    color: "from-pink-500 to-rose-500",
    subcategories: {
      transition: "Transitions",
      animation: "Animations",
      transform: "Transforms",
      transformOrigin: "Transform Origin",
    },
  },
  filters: {
    title: "Filters & Effects",
    icon: "Sparkles",
    color: "from-yellow-500 to-orange-500",
    subcategories: {
      filter: "Filters",
      backdropFilter: "Backdrop Filter",
      mixBlendMode: "Blend Modes",
      clipPath: "Clip Path",
    },
  },
  responsive: {
    title: "Responsive Design",
    icon: "Monitor",
    color: "from-cyan-500 to-blue-500",
    subcategories: {
      mediaQueries: "Media Queries",
      containerQueries: "Container Queries",
      viewport: "Viewport Units",
    },
  },
  interactivity: {
    title: "Interactivity",
    icon: "MousePointer",
    color: "from-violet-500 to-purple-500",
    subcategories: {
      cursor: "Cursor",
      pointerEvents: "Pointer Events",
      userSelect: "User Select",
      scrollBehavior: "Scroll Behavior",
    },
  },
  advanced: {
    title: "Advanced CSS",
    icon: "Code",
    color: "from-red-500 to-pink-500",
    subcategories: {
      customProperties: "Custom Properties",
      calc: "Calc & Functions",
      pseudoClasses: "Pseudo Classes",
      pseudoElements: "Pseudo Elements",
    },
  },
}

export const cssProperties: CSSProperty[] = [
  // DISPLAY PROPERTIES
  {
    name: "display",
    description: "Bir elementin görüntülenme şeklini belirler",
    syntax: "display: value;",
    values: ["block", "inline", "inline-block", "flex", "grid", "none", "contents"],
    example: "display: flex;",
    category: "layout",
    subcategory: "display",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "visibility",
    description: "Elementin görünürlüğünü kontrol eder (yer kaplar)",
    syntax: "visibility: value;",
    values: ["visible", "hidden", "collapse"],
    example: "visibility: hidden;",
    category: "layout",
    subcategory: "display",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "opacity",
    description: "Elementin saydamlık seviyesini belirler",
    syntax: "opacity: value;",
    values: ["0-1 arası değer"],
    example: "opacity: 0.5;",
    category: "colors",
    subcategory: "opacity",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "content-visibility",
    description: "İçerik görünürlüğünü kontrol eder (performans)",
    syntax: "content-visibility: value;",
    values: ["visible", "auto", "hidden"],
    example: "content-visibility: auto;",
    category: "layout",
    subcategory: "display",
    browserSupport: "Modern tarayıcılar",
  },

  // POSITION PROPERTIES
  {
    name: "position",
    description: "Elementin konumlandırma yöntemini belirler",
    syntax: "position: value;",
    values: ["static", "relative", "absolute", "fixed", "sticky"],
    example: "position: absolute;",
    category: "layout",
    subcategory: "position",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "top",
    description: "Konumlandırılmış elementin üstten uzaklığını belirler",
    syntax: "top: value;",
    values: ["auto", "length", "percentage"],
    example: "top: 20px;",
    category: "layout",
    subcategory: "position",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "right",
    description: "Konumlandırılmış elementin sağdan uzaklığını belirler",
    syntax: "right: value;",
    values: ["auto", "length", "percentage"],
    example: "right: 10%;",
    category: "layout",
    subcategory: "position",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "bottom",
    description: "Konumlandırılmış elementin alttan uzaklığını belirler",
    syntax: "bottom: value;",
    values: ["auto", "length", "percentage"],
    example: "bottom: 0;",
    category: "layout",
    subcategory: "position",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "left",
    description: "Konumlandırılmış elementin soldan uzaklığını belirler",
    syntax: "left: value;",
    values: ["auto", "length", "percentage"],
    example: "left: 50px;",
    category: "layout",
    subcategory: "position",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "z-index",
    description: "Konumlandırılmış elementin yığın sırasını belirler",
    syntax: "z-index: value;",
    values: ["auto", "integer"],
    example: "z-index: 999;",
    category: "layout",
    subcategory: "position",
    browserSupport: "Tüm tarayıcılar",
  },

  // FLEXBOX PROPERTIES
  {
    name: "flex-direction",
    description: "Flex container'daki öğelerin yönünü belirler",
    syntax: "flex-direction: value;",
    values: ["row", "row-reverse", "column", "column-reverse"],
    example: "flex-direction: column;",
    category: "layout",
    subcategory: "flexbox",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "justify-content",
    description: "Ana eksen boyunca hizalamayı kontrol eder",
    syntax: "justify-content: value;",
    values: ["flex-start", "flex-end", "center", "space-between", "space-around", "space-evenly"],
    example: "justify-content: center;",
    category: "layout",
    subcategory: "flexbox",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "align-items",
    description: "Çapraz eksen boyunca hizalamayı kontrol eder",
    syntax: "align-items: value;",
    values: ["stretch", "flex-start", "flex-end", "center", "baseline"],
    example: "align-items: center;",
    category: "layout",
    subcategory: "flexbox",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "flex-wrap",
    description: "Flex öğelerinin sarılıp sarılmayacağını belirler",
    syntax: "flex-wrap: value;",
    values: ["nowrap", "wrap", "wrap-reverse"],
    example: "flex-wrap: wrap;",
    category: "layout",
    subcategory: "flexbox",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "flex",
    description: "Flex öğesinin büyüme, küçülme ve temel boyutunu belirler",
    syntax: "flex: grow shrink basis;",
    values: ["auto", "initial", "none", "number"],
    example: "flex: 1;",
    category: "layout",
    subcategory: "flexbox",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "align-self",
    description: "Tek bir flex öğesinin hizalamasını geçersiz kılar",
    syntax: "align-self: value;",
    values: ["auto", "flex-start", "flex-end", "center", "baseline", "stretch"],
    example: "align-self: flex-end;",
    category: "layout",
    subcategory: "flexbox",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "gap",
    description: "Flex veya grid öğeleri arasındaki boşluğu belirler",
    syntax: "gap: value;",
    values: ["length", "percentage"],
    example: "gap: 1rem;",
    category: "layout",
    subcategory: "flexbox",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "flex-grow",
    description: "Flex öğesinin büyüme faktörünü belirler",
    syntax: "flex-grow: value;",
    values: ["number"],
    example: "flex-grow: 2;",
    category: "layout",
    subcategory: "flexbox",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "flex-shrink",
    description: "Flex öğesinin küçülme faktörünü belirler",
    syntax: "flex-shrink: value;",
    values: ["number"],
    example: "flex-shrink: 0;",
    category: "layout",
    subcategory: "flexbox",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "flex-basis",
    description: "Flex öğesinin temel boyutunu belirler",
    syntax: "flex-basis: value;",
    values: ["auto", "length", "percentage"],
    example: "flex-basis: 200px;",
    category: "layout",
    subcategory: "flexbox",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "align-content",
    description: "Çok satırlı flex container'da satırların hizalamasını kontrol eder",
    syntax: "align-content: value;",
    values: ["flex-start", "flex-end", "center", "space-between", "space-around", "stretch"],
    example: "align-content: space-between;",
    category: "layout",
    subcategory: "flexbox",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "order",
    description: "Flex veya grid öğesinin sırasını belirler",
    syntax: "order: value;",
    values: ["integer"],
    example: "order: -1;",
    category: "layout",
    subcategory: "flexbox",
    browserSupport: "Modern tarayıcılar",
  },

  // GRID PROPERTIES
  {
    name: "grid-template-columns",
    description: "Grid sütunlarının boyutlarını tanımlar",
    syntax: "grid-template-columns: value;",
    values: ["none", "length", "percentage", "fr", "repeat()"],
    example: "grid-template-columns: repeat(3, 1fr);",
    category: "layout",
    subcategory: "grid",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "grid-template-rows",
    description: "Grid satırlarının boyutlarını tanımlar",
    syntax: "grid-template-rows: value;",
    values: ["none", "length", "percentage", "fr", "repeat()"],
    example: "grid-template-rows: 100px auto;",
    category: "layout",
    subcategory: "grid",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "grid-column",
    description: "Grid öğesinin sütun konumunu belirler",
    syntax: "grid-column: start / end;",
    values: ["auto", "span n", "line number"],
    example: "grid-column: 1 / 3;",
    category: "layout",
    subcategory: "grid",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "grid-row",
    description: "Grid öğesinin satır konumunu belirler",
    syntax: "grid-row: start / end;",
    values: ["auto", "span n", "line number"],
    example: "grid-row: 1 / span 2;",
    category: "layout",
    subcategory: "grid",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "grid-area",
    description: "Grid öğesinin alanını belirler",
    syntax: "grid-area: row-start / col-start / row-end / col-end;",
    values: ["auto", "custom-ident", "span"],
    example: "grid-area: header;",
    category: "layout",
    subcategory: "grid",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "grid-template-areas",
    description: "Grid alanlarını isimlendirir",
    syntax: "grid-template-areas: 'area-names';",
    values: ["none", "string"],
    example: "grid-template-areas: 'header header' 'sidebar main';",
    category: "layout",
    subcategory: "grid",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "grid-auto-flow",
    description: "Otomatik yerleştirme algoritmasını kontrol eder",
    syntax: "grid-auto-flow: value;",
    values: ["row", "column", "dense", "row dense", "column dense"],
    example: "grid-auto-flow: dense;",
    category: "layout",
    subcategory: "grid",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "grid-auto-columns",
    description: "Otomatik oluşturulan sütunların boyutunu belirler",
    syntax: "grid-auto-columns: value;",
    values: ["auto", "length", "percentage", "fr", "min-content", "max-content"],
    example: "grid-auto-columns: 1fr;",
    category: "layout",
    subcategory: "grid",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "grid-auto-rows",
    description: "Otomatik oluşturulan satırların boyutunu belirler",
    syntax: "grid-auto-rows: value;",
    values: ["auto", "length", "percentage", "fr", "min-content", "max-content"],
    example: "grid-auto-rows: minmax(100px, auto);",
    category: "layout",
    subcategory: "grid",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "place-items",
    description: "align-items ve justify-items için kısayol",
    syntax: "place-items: align-items justify-items;",
    values: ["start", "end", "center", "stretch"],
    example: "place-items: center;",
    category: "layout",
    subcategory: "grid",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "place-content",
    description: "align-content ve justify-content için kısayol",
    syntax: "place-content: align-content justify-content;",
    values: ["start", "end", "center", "space-between", "space-around", "space-evenly"],
    example: "place-content: center;",
    category: "layout",
    subcategory: "grid",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "place-self",
    description: "align-self ve justify-self için kısayol",
    syntax: "place-self: align-self justify-self;",
    values: ["auto", "start", "end", "center", "stretch"],
    example: "place-self: center;",
    category: "layout",
    subcategory: "grid",
    browserSupport: "Modern tarayıcılar",
  },

  // FLOAT & CLEAR
  {
    name: "float",
    description: "Elementin yüzmesini sağlar",
    syntax: "float: value;",
    values: ["none", "left", "right"],
    example: "float: left;",
    category: "layout",
    subcategory: "float",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "clear",
    description: "Yüzen elementlerin etkisini temizler",
    syntax: "clear: value;",
    values: ["none", "left", "right", "both"],
    example: "clear: both;",
    category: "layout",
    subcategory: "float",
    browserSupport: "Tüm tarayıcılar",
  },

  // MULTI-COLUMN
  {
    name: "column-count",
    description: "Sütun sayısını belirler",
    syntax: "column-count: value;",
    values: ["auto", "number"],
    example: "column-count: 3;",
    category: "layout",
    subcategory: "columns",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "column-gap",
    description: "Sütunlar arası boşluğu belirler",
    syntax: "column-gap: value;",
    values: ["normal", "length"],
    example: "column-gap: 2rem;",
    category: "layout",
    subcategory: "columns",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "column-rule",
    description: "Sütunlar arası çizgiyi belirler",
    syntax: "column-rule: width style color;",
    values: ["width", "style", "color"],
    example: "column-rule: 1px solid #ccc;",
    category: "layout",
    subcategory: "columns",
    browserSupport: "Modern tarayıcılar",
  },

  // TYPOGRAPHY - FONT
  {
    name: "font-family",
    description: "Yazı tipi ailesini belirler",
    syntax: "font-family: family-name;",
    values: ["serif", "sans-serif", "monospace", "cursive", "fantasy"],
    example: "font-family: 'Arial', sans-serif;",
    category: "typography",
    subcategory: "font",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "font-size",
    description: "Yazı tipi boyutunu belirler",
    syntax: "font-size: value;",
    values: ["xx-small", "x-small", "small", "medium", "large", "x-large", "xx-large", "length", "percentage"],
    example: "font-size: 16px;",
    category: "typography",
    subcategory: "font",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "font-weight",
    description: "Yazı tipi kalınlığını belirler",
    syntax: "font-weight: value;",
    values: ["normal", "bold", "bolder", "lighter", "100-900"],
    example: "font-weight: 700;",
    category: "typography",
    subcategory: "font",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "font-style",
    description: "Yazı tipi stilini belirler",
    syntax: "font-style: value;",
    values: ["normal", "italic", "oblique"],
    example: "font-style: italic;",
    category: "typography",
    subcategory: "font",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "font-variant",
    description: "Yazı tipi varyantını belirler",
    syntax: "font-variant: value;",
    values: ["normal", "small-caps"],
    example: "font-variant: small-caps;",
    category: "typography",
    subcategory: "font",
    browserSupport: "Tüm tarayıcılar",
  },

  // TYPOGRAPHY - TEXT
  {
    name: "color",
    description: "Metin rengini belirler",
    syntax: "color: value;",
    values: ["color-name", "hex", "rgb", "rgba", "hsl", "hsla"],
    example: "color: #3b82f6;",
    category: "typography",
    subcategory: "text",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "text-align",
    description: "Metnin yatay hizalamasını belirler",
    syntax: "text-align: value;",
    values: ["left", "right", "center", "justify"],
    example: "text-align: center;",
    category: "typography",
    subcategory: "text",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "text-decoration",
    description: "Metin dekorasyonunu belirler",
    syntax: "text-decoration: value;",
    values: ["none", "underline", "overline", "line-through"],
    example: "text-decoration: underline;",
    category: "typography",
    subcategory: "textDecoration",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "text-transform",
    description: "Metin dönüşümünü belirler",
    syntax: "text-transform: value;",
    values: ["none", "capitalize", "uppercase", "lowercase"],
    example: "text-transform: uppercase;",
    category: "typography",
    subcategory: "textTransform",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "line-height",
    description: "Satır yüksekliğini belirler",
    syntax: "line-height: value;",
    values: ["normal", "number", "length", "percentage"],
    example: "line-height: 1.6;",
    category: "typography",
    subcategory: "lineHeight",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "letter-spacing",
    description: "Harfler arası boşluğu belirler",
    syntax: "letter-spacing: value;",
    values: ["normal", "length"],
    example: "letter-spacing: 2px;",
    category: "typography",
    subcategory: "lineHeight",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "word-spacing",
    description: "Kelimeler arası boşluğu belirler",
    syntax: "word-spacing: value;",
    values: ["normal", "length"],
    example: "word-spacing: 5px;",
    category: "typography",
    subcategory: "lineHeight",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "text-shadow",
    description: "Metne gölge ekler",
    syntax: "text-shadow: h-offset v-offset blur color;",
    values: ["none", "h-shadow v-shadow blur-radius color"],
    example: "text-shadow: 2px 2px 4px rgba(0,0,0,0.5);",
    category: "typography",
    subcategory: "textDecoration",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "text-indent",
    description: "İlk satır girintisini belirler",
    syntax: "text-indent: value;",
    values: ["length", "percentage"],
    example: "text-indent: 2em;",
    category: "typography",
    subcategory: "text",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "text-overflow",
    description: "Taşan metnin nasıl gösterileceğini belirler",
    syntax: "text-overflow: value;",
    values: ["clip", "ellipsis"],
    example: "text-overflow: ellipsis;",
    category: "typography",
    subcategory: "text",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "white-space",
    description: "Boşluk karakterlerinin işlenmesini kontrol eder",
    syntax: "white-space: value;",
    values: ["normal", "nowrap", "pre", "pre-wrap", "pre-line"],
    example: "white-space: nowrap;",
    category: "typography",
    subcategory: "text",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "word-break",
    description: "Kelime kırılma kurallarını belirler",
    syntax: "word-break: value;",
    values: ["normal", "break-all", "keep-all", "break-word"],
    example: "word-break: break-word;",
    category: "typography",
    subcategory: "text",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "word-wrap",
    description: "Uzun kelimelerin kırılmasını kontrol eder",
    syntax: "word-wrap: value;",
    values: ["normal", "break-word"],
    example: "word-wrap: break-word;",
    category: "typography",
    subcategory: "text",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "writing-mode",
    description: "Yazı yönünü belirler",
    syntax: "writing-mode: value;",
    values: ["horizontal-tb", "vertical-rl", "vertical-lr"],
    example: "writing-mode: vertical-rl;",
    category: "typography",
    subcategory: "text",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "text-decoration-line",
    description: "Metin dekorasyon çizgisini belirler",
    syntax: "text-decoration-line: value;",
    values: ["none", "underline", "overline", "line-through"],
    example: "text-decoration-line: underline;",
    category: "typography",
    subcategory: "textDecoration",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "text-decoration-color",
    description: "Metin dekorasyon rengini belirler",
    syntax: "text-decoration-color: value;",
    values: ["color"],
    example: "text-decoration-color: red;",
    category: "typography",
    subcategory: "textDecoration",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "text-decoration-style",
    description: "Metin dekorasyon stilini belirler",
    syntax: "text-decoration-style: value;",
    values: ["solid", "double", "dotted", "dashed", "wavy"],
    example: "text-decoration-style: wavy;",
    category: "typography",
    subcategory: "textDecoration",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "text-decoration-thickness",
    description: "Metin dekorasyon kalınlığını belirler",
    syntax: "text-decoration-thickness: value;",
    values: ["auto", "from-font", "length", "percentage"],
    example: "text-decoration-thickness: 2px;",
    category: "typography",
    subcategory: "textDecoration",
    browserSupport: "Modern tarayıcılar",
  },

  // COLORS & BACKGROUNDS
  {
    name: "background-color",
    description: "Arka plan rengini belirler",
    syntax: "background-color: value;",
    values: ["transparent", "color-name", "hex", "rgb", "rgba", "hsl", "hsla"],
    example: "background-color: #f3f4f6;",
    category: "colors",
    subcategory: "background",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "background-image",
    description: "Arka plan görselini belirler",
    syntax: "background-image: value;",
    values: ["none", "url()", "linear-gradient()", "radial-gradient()"],
    example: "background-image: url('image.jpg');",
    category: "colors",
    subcategory: "background",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "background-size",
    description: "Arka plan görselinin boyutunu belirler",
    syntax: "background-size: value;",
    values: ["auto", "cover", "contain", "length", "percentage"],
    example: "background-size: cover;",
    category: "colors",
    subcategory: "background",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "background-position",
    description: "Arka plan görselinin konumunu belirler",
    syntax: "background-position: value;",
    values: ["left", "center", "right", "top", "bottom", "length", "percentage"],
    example: "background-position: center;",
    category: "colors",
    subcategory: "background",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "background-repeat",
    description: "Arka plan görselinin tekrarlanmasını kontrol eder",
    syntax: "background-repeat: value;",
    values: ["repeat", "repeat-x", "repeat-y", "no-repeat", "space", "round"],
    example: "background-repeat: no-repeat;",
    category: "colors",
    subcategory: "background",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "background-attachment",
    description: "Arka plan görselinin kaydırma davranışını belirler",
    syntax: "background-attachment: value;",
    values: ["scroll", "fixed", "local"],
    example: "background-attachment: fixed;",
    category: "colors",
    subcategory: "background",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "background-clip",
    description: "Arka planın boyama alanını belirler",
    syntax: "background-clip: value;",
    values: ["border-box", "padding-box", "content-box", "text"],
    example: "background-clip: text;",
    category: "colors",
    subcategory: "background",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "background-origin",
    description: "Arka plan konumlandırma alanını belirler",
    syntax: "background-origin: value;",
    values: ["border-box", "padding-box", "content-box"],
    example: "background-origin: content-box;",
    category: "colors",
    subcategory: "background",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "background-blend-mode",
    description: "Arka plan katmanlarının karışım modunu belirler",
    syntax: "background-blend-mode: value;",
    values: ["normal", "multiply", "screen", "overlay", "darken", "lighten"],
    example: "background-blend-mode: multiply;",
    category: "colors",
    subcategory: "background",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "linear-gradient",
    description: "Doğrusal gradyan oluşturur",
    syntax: "background-image: linear-gradient(direction, color-stop1, color-stop2, ...);",
    values: ["to top", "to right", "to bottom", "to left", "angle", "colors"],
    example: "background-image: linear-gradient(to right, #3b82f6, #8b5cf6);",
    category: "colors",
    subcategory: "gradient",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "radial-gradient",
    description: "Radyal gradyan oluşturur",
    syntax: "background-image: radial-gradient(shape size at position, color-stop1, color-stop2, ...);",
    values: ["circle", "ellipse", "closest-side", "farthest-corner", "colors"],
    example: "background-image: radial-gradient(circle, #3b82f6, #8b5cf6);",
    category: "colors",
    subcategory: "gradient",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "conic-gradient",
    description: "Konik gradyan oluşturur",
    syntax: "background-image: conic-gradient(from angle at position, color-stop1, color-stop2, ...);",
    values: ["from angle", "at position", "colors"],
    example: "background-image: conic-gradient(from 0deg, red, yellow, green, blue, red);",
    category: "colors",
    subcategory: "gradient",
    browserSupport: "Modern tarayıcılar",
  },

  // BOX MODEL
  {
    name: "width",
    description: "Elementin genişliğini belirler",
    syntax: "width: value;",
    values: ["auto", "length", "percentage"],
    example: "width: 300px;",
    category: "boxModel",
    subcategory: "width",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "height",
    description: "Elementin yüksekliğini belirler",
    syntax: "height: value;",
    values: ["auto", "length", "percentage"],
    example: "height: 200px;",
    category: "boxModel",
    subcategory: "width",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "max-width",
    description: "Elementin maksimum genişliğini belirler",
    syntax: "max-width: value;",
    values: ["none", "length", "percentage"],
    example: "max-width: 1200px;",
    category: "boxModel",
    subcategory: "width",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "min-width",
    description: "Elementin minimum genişliğini belirler",
    syntax: "min-width: value;",
    values: ["length", "percentage"],
    example: "min-width: 320px;",
    category: "boxModel",
    subcategory: "width",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "max-height",
    description: "Elementin maksimum yüksekliğini belirler",
    syntax: "max-height: value;",
    values: ["none", "length", "percentage"],
    example: "max-height: 500px;",
    category: "boxModel",
    subcategory: "width",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "min-height",
    description: "Elementin minimum yüksekliğini belirler",
    syntax: "min-height: value;",
    values: ["length", "percentage"],
    example: "min-height: 100px;",
    category: "boxModel",
    subcategory: "width",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "margin",
    description: "Elementin dış boşluğunu belirler",
    syntax: "margin: value;",
    values: ["auto", "length", "percentage"],
    example: "margin: 20px;",
    category: "boxModel",
    subcategory: "margin",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "margin-top",
    description: "Elementin üst dış boşluğunu belirler",
    syntax: "margin-top: value;",
    values: ["auto", "length", "percentage"],
    example: "margin-top: 10px;",
    category: "boxModel",
    subcategory: "margin",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "margin-right",
    description: "Elementin sağ dış boşluğunu belirler",
    syntax: "margin-right: value;",
    values: ["auto", "length", "percentage"],
    example: "margin-right: 15px;",
    category: "boxModel",
    subcategory: "margin",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "margin-bottom",
    description: "Elementin alt dış boşluğunu belirler",
    syntax: "margin-bottom: value;",
    values: ["auto", "length", "percentage"],
    example: "margin-bottom: 20px;",
    category: "boxModel",
    subcategory: "margin",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "margin-left",
    description: "Elementin sol dış boşluğunu belirler",
    syntax: "margin-left: value;",
    values: ["auto", "length", "percentage"],
    example: "margin-left: 10px;",
    category: "boxModel",
    subcategory: "margin",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "padding",
    description: "Elementin iç boşluğunu belirler",
    syntax: "padding: value;",
    values: ["length", "percentage"],
    example: "padding: 20px;",
    category: "boxModel",
    subcategory: "padding",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "padding-top",
    description: "Elementin üst iç boşluğunu belirler",
    syntax: "padding-top: value;",
    values: ["length", "percentage"],
    example: "padding-top: 10px;",
    category: "boxModel",
    subcategory: "padding",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "padding-right",
    description: "Elementin sağ iç boşluğunu belirler",
    syntax: "padding-right: value;",
    values: ["length", "percentage"],
    example: "padding-right: 15px;",
    category: "boxModel",
    subcategory: "padding",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "padding-bottom",
    description: "Elementin alt iç boşluğunu belirler",
    syntax: "padding-bottom: value;",
    values: ["length", "percentage"],
    example: "padding-bottom: 20px;",
    category: "boxModel",
    subcategory: "padding",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "padding-left",
    description: "Elementin sol iç boşluğunu belirler",
    syntax: "padding-left: value;",
    values: ["length", "percentage"],
    example: "padding-left: 10px;",
    category: "boxModel",
    subcategory: "padding",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "box-sizing",
    description: "Box model hesaplama yöntemini belirler",
    syntax: "box-sizing: value;",
    values: ["content-box", "border-box"],
    example: "box-sizing: border-box;",
    category: "boxModel",
    subcategory: "boxSizing",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "aspect-ratio",
    description: "Elementin en-boy oranını belirler",
    syntax: "aspect-ratio: value;",
    values: ["auto", "width / height"],
    example: "aspect-ratio: 16 / 9;",
    category: "boxModel",
    subcategory: "width",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "object-fit",
    description: "Değiştirilen içeriğin (img, video) nasıl sığdırılacağını belirler",
    syntax: "object-fit: value;",
    values: ["fill", "contain", "cover", "none", "scale-down"],
    example: "object-fit: cover;",
    category: "boxModel",
    subcategory: "width",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "object-position",
    description: "Değiştirilen içeriğin konumunu belirler",
    syntax: "object-position: value;",
    values: ["position"],
    example: "object-position: center top;",
    category: "boxModel",
    subcategory: "width",
    browserSupport: "Modern tarayıcılar",
  },

  // BORDERS
  {
    name: "border",
    description: "Elementin kenarlığını belirler (kısayol)",
    syntax: "border: width style color;",
    values: ["width", "style", "color"],
    example: "border: 2px solid #3b82f6;",
    category: "borders",
    subcategory: "border",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "border-width",
    description: "Kenarlık kalınlığını belirler",
    syntax: "border-width: value;",
    values: ["thin", "medium", "thick", "length"],
    example: "border-width: 2px;",
    category: "borders",
    subcategory: "border",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "border-style",
    description: "Kenarlık stilini belirler",
    syntax: "border-style: value;",
    values: ["none", "solid", "dashed", "dotted", "double", "groove", "ridge", "inset", "outset"],
    example: "border-style: solid;",
    category: "borders",
    subcategory: "border",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "border-color",
    description: "Kenarlık rengini belirler",
    syntax: "border-color: value;",
    values: ["color-name", "hex", "rgb", "rgba", "hsl", "hsla"],
    example: "border-color: #3b82f6;",
    category: "borders",
    subcategory: "border",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "border-radius",
    description: "Köşe yuvarlaklığını belirler",
    syntax: "border-radius: value;",
    values: ["length", "percentage"],
    example: "border-radius: 8px;",
    category: "borders",
    subcategory: "borderRadius",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "border-top-left-radius",
    description: "Sol üst köşe yuvarlaklığını belirler",
    syntax: "border-top-left-radius: value;",
    values: ["length", "percentage"],
    example: "border-top-left-radius: 10px;",
    category: "borders",
    subcategory: "borderRadius",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "border-top-right-radius",
    description: "Sağ üst köşe yuvarlaklığını belirler",
    syntax: "border-top-right-radius: value;",
    values: ["length", "percentage"],
    example: "border-top-right-radius: 10px;",
    category: "borders",
    subcategory: "borderRadius",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "border-bottom-left-radius",
    description: "Sol alt köşe yuvarlaklığını belirler",
    syntax: "border-bottom-left-radius: value;",
    values: ["length", "percentage"],
    example: "border-bottom-left-radius: 10px;",
    category: "borders",
    subcategory: "borderRadius",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "border-bottom-right-radius",
    description: "Sağ alt köşe yuvarlaklığını belirler",
    syntax: "border-bottom-right-radius: value;",
    values: ["length", "percentage"],
    example: "border-bottom-right-radius: 10px;",
    category: "borders",
    subcategory: "borderRadius",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "box-shadow",
    description: "Elementin gölgesini belirler",
    syntax: "box-shadow: h-offset v-offset blur spread color;",
    values: ["none", "h-shadow v-shadow blur-radius spread-radius color"],
    example: "box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);",
    category: "borders",
    subcategory: "boxShadow",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "outline",
    description: "Elementin dış çizgisini belirler",
    syntax: "outline: width style color;",
    values: ["width", "style", "color"],
    example: "outline: 2px solid #3b82f6;",
    category: "borders",
    subcategory: "outline",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "outline-offset",
    description: "Outline ile element arasındaki boşluğu belirler",
    syntax: "outline-offset: value;",
    values: ["length"],
    example: "outline-offset: 4px;",
    category: "borders",
    subcategory: "outline",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "border-image",
    description: "Kenarlık görseli belirler",
    syntax: "border-image: source slice width outset repeat;",
    values: ["source", "slice", "width", "outset", "repeat"],
    example: "border-image: url('border.png') 30 round;",
    category: "borders",
    subcategory: "border",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "border-image-source",
    description: "Kenarlık görseli kaynağını belirler",
    syntax: "border-image-source: value;",
    values: ["none", "url()"],
    example: "border-image-source: url('border.png');",
    category: "borders",
    subcategory: "border",
    browserSupport: "Modern tarayıcılar",
  },

  // ANIMATIONS & TRANSITIONS
  {
    name: "transition",
    description: "CSS geçiş efektini belirler (kısayol)",
    syntax: "transition: property duration timing-function delay;",
    values: ["property", "duration", "timing-function", "delay"],
    example: "transition: all 0.3s ease;",
    category: "animations",
    subcategory: "transition",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "transition-property",
    description: "Geçiş efekti uygulanacak özellikleri belirler",
    syntax: "transition-property: value;",
    values: ["none", "all", "property-name"],
    example: "transition-property: opacity, transform;",
    category: "animations",
    subcategory: "transition",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "transition-duration",
    description: "Geçiş efektinin süresini belirler",
    syntax: "transition-duration: value;",
    values: ["time"],
    example: "transition-duration: 0.3s;",
    category: "animations",
    subcategory: "transition",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "transition-timing-function",
    description: "Geçiş efektinin zamanlama fonksiyonunu belirler",
    syntax: "transition-timing-function: value;",
    values: ["ease", "linear", "ease-in", "ease-out", "ease-in-out", "cubic-bezier()"],
    example: "transition-timing-function: ease-in-out;",
    category: "animations",
    subcategory: "transition",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "transition-delay",
    description: "Geçiş efektinin başlama gecikmesini belirler",
    syntax: "transition-delay: value;",
    values: ["time"],
    example: "transition-delay: 0.1s;",
    category: "animations",
    subcategory: "transition",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "animation",
    description: "CSS animasyonunu belirler (kısayol)",
    syntax: "animation: name duration timing-function delay iteration-count direction fill-mode;",
    values: ["name", "duration", "timing-function", "delay", "iteration-count", "direction", "fill-mode"],
    example: "animation: slideIn 1s ease-in-out;",
    category: "animations",
    subcategory: "animation",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "animation-name",
    description: "Animasyon adını belirler",
    syntax: "animation-name: value;",
    values: ["none", "keyframe-name"],
    example: "animation-name: fadeIn;",
    category: "animations",
    subcategory: "animation",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "animation-duration",
    description: "Animasyon süresini belirler",
    syntax: "animation-duration: value;",
    values: ["time"],
    example: "animation-duration: 2s;",
    category: "animations",
    subcategory: "animation",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "animation-iteration-count",
    description: "Animasyonun tekrar sayısını belirler",
    syntax: "animation-iteration-count: value;",
    values: ["number", "infinite"],
    example: "animation-iteration-count: infinite;",
    category: "animations",
    subcategory: "animation",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "animation-timing-function",
    description: "Animasyon zamanlama fonksiyonunu belirler",
    syntax: "animation-timing-function: value;",
    values: ["ease", "linear", "ease-in", "ease-out", "ease-in-out", "cubic-bezier()"],
    example: "animation-timing-function: cubic-bezier(0.4, 0, 0.2, 1);",
    category: "animations",
    subcategory: "animation",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "animation-delay",
    description: "Animasyon başlama gecikmesini belirler",
    syntax: "animation-delay: value;",
    values: ["time"],
    example: "animation-delay: 0.5s;",
    category: "animations",
    subcategory: "animation",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "animation-direction",
    description: "Animasyon yönünü belirler",
    syntax: "animation-direction: value;",
    values: ["normal", "reverse", "alternate", "alternate-reverse"],
    example: "animation-direction: alternate;",
    category: "animations",
    subcategory: "animation",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "animation-fill-mode",
    description: "Animasyon öncesi ve sonrası stilleri belirler",
    syntax: "animation-fill-mode: value;",
    values: ["none", "forwards", "backwards", "both"],
    example: "animation-fill-mode: forwards;",
    category: "animations",
    subcategory: "animation",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "animation-play-state",
    description: "Animasyonun oynatma durumunu kontrol eder",
    syntax: "animation-play-state: value;",
    values: ["running", "paused"],
    example: "animation-play-state: paused;",
    category: "animations",
    subcategory: "animation",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "transform",
    description: "Elementin dönüşümünü belirler",
    syntax: "transform: function();",
    values: [
      "translate()",
      "rotate()",
      "scale()",
      "skew()",
      "matrix()",
      "translateX()",
      "translateY()",
      "scaleX()",
      "scaleY()",
    ],
    example: "transform: rotate(45deg);",
    category: "animations",
    subcategory: "transform",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "transform-origin",
    description: "Dönüşüm merkezini belirler",
    syntax: "transform-origin: x-axis y-axis z-axis;",
    values: ["left", "center", "right", "top", "bottom", "length", "percentage"],
    example: "transform-origin: center center;",
    category: "animations",
    subcategory: "transformOrigin",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "perspective",
    description: "3D perspektif mesafesini belirler",
    syntax: "perspective: value;",
    values: ["none", "length"],
    example: "perspective: 1000px;",
    category: "animations",
    subcategory: "transform",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "perspective-origin",
    description: "3D perspektif merkezini belirler",
    syntax: "perspective-origin: x-axis y-axis;",
    values: ["left", "center", "right", "top", "bottom", "length", "percentage"],
    example: "perspective-origin: 50% 50%;",
    category: "animations",
    subcategory: "transform",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "transform-style",
    description: "3D dönüşüm stilini belirler",
    syntax: "transform-style: value;",
    values: ["flat", "preserve-3d"],
    example: "transform-style: preserve-3d;",
    category: "animations",
    subcategory: "transform",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "backface-visibility",
    description: "Elementin arka yüzünün görünürlüğünü kontrol eder",
    syntax: "backface-visibility: value;",
    values: ["visible", "hidden"],
    example: "backface-visibility: hidden;",
    category: "animations",
    subcategory: "transform",
    browserSupport: "Modern tarayıcılar",
  },

  // FILTERS & EFFECTS
  {
    name: "filter",
    description: "Görsel efektler uygular",
    syntax: "filter: function();",
    values: [
      "blur()",
      "brightness()",
      "contrast()",
      "grayscale()",
      "hue-rotate()",
      "invert()",
      "saturate()",
      "sepia()",
      "drop-shadow()",
    ],
    example: "filter: blur(5px);",
    category: "filters",
    subcategory: "filter",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "backdrop-filter",
    description: "Arka plana görsel efektler uygular",
    syntax: "backdrop-filter: function();",
    values: ["blur()", "brightness()", "contrast()", "grayscale()", "saturate()"],
    example: "backdrop-filter: blur(10px);",
    category: "filters",
    subcategory: "backdropFilter",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "mix-blend-mode",
    description: "Karışım modunu belirler",
    syntax: "mix-blend-mode: value;",
    values: [
      "normal",
      "multiply",
      "screen",
      "overlay",
      "darken",
      "lighten",
      "color-dodge",
      "color-burn",
      "difference",
      "exclusion",
    ],
    example: "mix-blend-mode: multiply;",
    category: "filters",
    subcategory: "mixBlendMode",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "clip-path",
    description: "Elementin kırpma yolunu belirler",
    syntax: "clip-path: function();",
    values: ["circle()", "ellipse()", "polygon()", "inset()", "url()"],
    example: "clip-path: circle(50%);",
    category: "filters",
    subcategory: "clipPath",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "isolation",
    description: "Yeni bir yığınlama bağlamı oluşturur",
    syntax: "isolation: value;",
    values: ["auto", "isolate"],
    example: "isolation: isolate;",
    category: "filters",
    subcategory: "mixBlendMode",
    browserSupport: "Modern tarayıcılar",
  },

  // INTERACTIVITY
  {
    name: "cursor",
    description: "Fare imleci stilini belirler",
    syntax: "cursor: value;",
    values: [
      "auto",
      "default",
      "pointer",
      "text",
      "move",
      "wait",
      "help",
      "not-allowed",
      "grab",
      "grabbing",
      "zoom-in",
      "zoom-out",
    ],
    example: "cursor: pointer;",
    category: "interactivity",
    subcategory: "cursor",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "pointer-events",
    description: "Fare olaylarının işlenmesini kontrol eder",
    syntax: "pointer-events: value;",
    values: ["auto", "none"],
    example: "pointer-events: none;",
    category: "interactivity",
    subcategory: "pointerEvents",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "user-select",
    description: "Metin seçimini kontrol eder",
    syntax: "user-select: value;",
    values: ["auto", "none", "text", "all"],
    example: "user-select: none;",
    category: "interactivity",
    subcategory: "userSelect",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "scroll-behavior",
    description: "Kaydırma davranışını belirler",
    syntax: "scroll-behavior: value;",
    values: ["auto", "smooth"],
    example: "scroll-behavior: smooth;",
    category: "interactivity",
    subcategory: "scrollBehavior",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "overflow",
    description: "Taşan içeriğin nasıl işleneceğini belirler",
    syntax: "overflow: value;",
    values: ["visible", "hidden", "scroll", "auto"],
    example: "overflow: hidden;",
    category: "interactivity",
    subcategory: "scrollBehavior",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "overflow-x",
    description: "Yatay taşan içeriğin nasıl işleneceğini belirler",
    syntax: "overflow-x: value;",
    values: ["visible", "hidden", "scroll", "auto"],
    example: "overflow-x: auto;",
    category: "interactivity",
    subcategory: "scrollBehavior",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "overflow-y",
    description: "Dikey taşan içeriğin nasıl işleneceğini belirler",
    syntax: "overflow-y: value;",
    values: ["visible", "hidden", "scroll", "auto"],
    example: "overflow-y: scroll;",
    category: "interactivity",
    subcategory: "scrollBehavior",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "resize",
    description: "Kullanıcının elementi yeniden boyutlandırmasına izin verir",
    syntax: "resize: value;",
    values: ["none", "both", "horizontal", "vertical"],
    example: "resize: both;",
    category: "interactivity",
    subcategory: "userSelect",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "scroll-snap-type",
    description: "Kaydırma yakalama türünü belirler",
    syntax: "scroll-snap-type: axis strictness;",
    values: ["none", "x", "y", "both", "mandatory", "proximity"],
    example: "scroll-snap-type: y mandatory;",
    category: "interactivity",
    subcategory: "scrollBehavior",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "scroll-snap-align",
    description: "Kaydırma yakalama hizalamasını belirler",
    syntax: "scroll-snap-align: value;",
    values: ["none", "start", "end", "center"],
    example: "scroll-snap-align: start;",
    category: "interactivity",
    subcategory: "scrollBehavior",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "overscroll-behavior",
    description: "Aşırı kaydırma davranışını kontrol eder",
    syntax: "overscroll-behavior: value;",
    values: ["auto", "contain", "none"],
    example: "overscroll-behavior: contain;",
    category: "interactivity",
    subcategory: "scrollBehavior",
    browserSupport: "Modern tarayıcılar",
  },

  // ADVANCED CSS
  {
    name: "--custom-property",
    description: "CSS özel değişkeni tanımlar",
    syntax: "--property-name: value;",
    values: ["any value"],
    example: "--primary-color: #3b82f6;",
    category: "advanced",
    subcategory: "customProperties",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "var()",
    description: "CSS özel değişkenini kullanır",
    syntax: "property: var(--custom-property, fallback);",
    values: ["--custom-property", "fallback"],
    example: "color: var(--primary-color, blue);",
    category: "advanced",
    subcategory: "customProperties",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "calc()",
    description: "Matematiksel hesaplama yapar",
    syntax: "property: calc(expression);",
    values: ["+", "-", "*", "/"],
    example: "width: calc(100% - 50px);",
    category: "advanced",
    subcategory: "calc",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: ":hover",
    description: "Fare üzerine gelindiğinde stil uygular",
    syntax: "selector:hover { }",
    values: ["any CSS properties"],
    example: "button:hover { background-color: blue; }",
    category: "advanced",
    subcategory: "pseudoClasses",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: ":focus",
    description: "Element odaklandığında stil uygular",
    syntax: "selector:focus { }",
    values: ["any CSS properties"],
    example: "input:focus { border-color: blue; }",
    category: "advanced",
    subcategory: "pseudoClasses",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: ":active",
    description: "Element aktif olduğunda stil uygular",
    syntax: "selector:active { }",
    values: ["any CSS properties"],
    example: "button:active { transform: scale(0.95); }",
    category: "advanced",
    subcategory: "pseudoClasses",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: ":nth-child()",
    description: "Belirli sıradaki çocuk elementleri seçer",
    syntax: "selector:nth-child(n) { }",
    values: ["number", "odd", "even", "formula"],
    example: "li:nth-child(2n) { background: gray; }",
    category: "advanced",
    subcategory: "pseudoClasses",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: ":first-child",
    description: "İlk çocuk elementi seçer",
    syntax: "selector:first-child { }",
    values: ["any CSS properties"],
    example: "p:first-child { font-weight: bold; }",
    category: "advanced",
    subcategory: "pseudoClasses",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: ":last-child",
    description: "Son çocuk elementi seçer",
    syntax: "selector:last-child { }",
    values: ["any CSS properties"],
    example: "p:last-child { margin-bottom: 0; }",
    category: "advanced",
    subcategory: "pseudoClasses",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: ":not()",
    description: "Belirtilen seçiciyle eşleşmeyen elementleri seçer",
    syntax: "selector:not(selector) { }",
    values: ["selector"],
    example: "p:not(.special) { color: gray; }",
    category: "advanced",
    subcategory: "pseudoClasses",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: ":disabled",
    description: "Devre dışı elementleri seçer",
    syntax: "selector:disabled { }",
    values: ["any CSS properties"],
    example: "input:disabled { opacity: 0.5; }",
    category: "advanced",
    subcategory: "pseudoClasses",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: ":checked",
    description: "İşaretli form elementlerini seçer",
    syntax: "selector:checked { }",
    values: ["any CSS properties"],
    example: "input:checked { background: blue; }",
    category: "advanced",
    subcategory: "pseudoClasses",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "::before",
    description: "Element öncesine içerik ekler",
    syntax: "selector::before { content: ''; }",
    values: ["content", "any CSS properties"],
    example: "p::before { content: '→ '; }",
    category: "advanced",
    subcategory: "pseudoElements",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "::after",
    description: "Element sonrasına içerik ekler",
    syntax: "selector::after { content: ''; }",
    values: ["content", "any CSS properties"],
    example: "p::after { content: ' ←'; }",
    category: "advanced",
    subcategory: "pseudoElements",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "::first-letter",
    description: "İlk harfi seçer",
    syntax: "selector::first-letter { }",
    values: ["any CSS properties"],
    example: "p::first-letter { font-size: 2em; }",
    category: "advanced",
    subcategory: "pseudoElements",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "::first-line",
    description: "İlk satırı seçer",
    syntax: "selector::first-line { }",
    values: ["any CSS properties"],
    example: "p::first-line { font-weight: bold; }",
    category: "advanced",
    subcategory: "pseudoElements",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "::selection",
    description: "Seçili metni stillendirir",
    syntax: "selector::selection { }",
    values: ["color", "background-color"],
    example: "::selection { background: yellow; }",
    category: "advanced",
    subcategory: "pseudoElements",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "::placeholder",
    description: "Input placeholder metnini stillendirir",
    syntax: "selector::placeholder { }",
    values: ["any CSS properties"],
    example: "input::placeholder { color: gray; }",
    category: "advanced",
    subcategory: "pseudoElements",
    browserSupport: "Modern tarayıcılar",
  },

  // RESPONSIVE DESIGN
  {
    name: "@media",
    description: "Medya sorguları ile responsive tasarım oluşturur",
    syntax: "@media (condition) { }",
    values: ["screen", "print", "min-width", "max-width", "orientation"],
    example: "@media (max-width: 768px) { .container { width: 100%; } }",
    category: "responsive",
    subcategory: "mediaQueries",
    browserSupport: "Tüm tarayıcılar",
  },
  {
    name: "@container",
    description: "Container sorguları ile responsive tasarım oluşturur",
    syntax: "@container (condition) { }",
    values: ["min-width", "max-width", "orientation"],
    example: "@container (min-width: 400px) { .card { display: grid; } }",
    category: "responsive",
    subcategory: "containerQueries",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "container-type",
    description: "Container sorgu türünü belirler",
    syntax: "container-type: value;",
    values: ["normal", "size", "inline-size"],
    example: "container-type: inline-size;",
    category: "responsive",
    subcategory: "containerQueries",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "container-name",
    description: "Container adını belirler",
    syntax: "container-name: value;",
    values: ["none", "custom-ident"],
    example: "container-name: sidebar;",
    category: "responsive",
    subcategory: "containerQueries",
    browserSupport: "Modern tarayıcılar",
  },

  // VIEWPORT UNITS
  {
    name: "vw",
    description: "Viewport genişliğinin yüzdesi (1vw = viewport genişliğinin %1'i)",
    syntax: "property: value vw;",
    values: ["number"],
    example: "width: 50vw;",
    category: "responsive",
    subcategory: "viewport",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "vh",
    description: "Viewport yüksekliğinin yüzdesi (1vh = viewport yüksekliğinin %1'i)",
    syntax: "property: value vh;",
    values: ["number"],
    example: "height: 100vh;",
    category: "responsive",
    subcategory: "viewport",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "vmin",
    description: "Viewport'un küçük boyutunun yüzdesi",
    syntax: "property: value vmin;",
    values: ["number"],
    example: "font-size: 5vmin;",
    category: "responsive",
    subcategory: "viewport",
    browserSupport: "Modern tarayıcılar",
  },
  {
    name: "vmax",
    description: "Viewport'un büyük boyutunun yüzdesi",
    syntax: "property: value vmax;",
    values: ["number"],
    example: "font-size: 5vmax;",
    category: "responsive",
    subcategory: "viewport",
    browserSupport: "Modern tarayıcılar",
  },

  // ADDITIONAL PROPERTIES
  {
    name: "will-change",
    description: "Değişecek özellikleri tarayıcıya bildirir (performans optimizasyonu)",
    syntax: "will-change: value;",
    values: ["auto", "scroll-position", "contents", "property-name"],
    example: "will-change: transform;",
    category: "animations",
    subcategory: "animation",
    browserSupport: "Modern tarayıcılar",
  },
]
